# 1.

In [ ]:
'''create a package named 'cricket' which will contain modules names batsman and bowler
create following functions in respective modules.import the package and call all these
functions in your program.
batsman:findaverage(runs,matches),strikerate(runs,balls)
bowler:findavg(runs,wickets),economyrate(overs,runs) ''' 

In [16]:
from cricket import batsman,bowler
print('for batsman')
runs=int(input('enter runs:'))
matches=int(input('enter matches:'))
balls=int(input('enter balls:'))
print('batsman average:',batsman.findaverage(runs,matches))
print('batsman strikerate:',batsman.strikerate(runs,balls))
print('')
print('for bowler')
runs=int(input('enter runs:'))
wicket=int(input('enter wickets:'))
overs=int(input('enter overs:'))
print('bowler average:',bowler.findavg(runs,wicket))
print('batsman economyrate:',bowler.economyrate(overs,runs))

for batsman


enter runs: 120
enter matches: 2
enter balls: 40


batsman average: 60.0
batsman strikerate: 300.0

for bowler


enter runs: 40
enter wickets: 4
enter overs: 6


bowler average: 10.0
batsman economyrate: 6.666666666666667


# 2.

In [ ]:
'''write a python function to find whether the number is prime or not
def isPrime(num)'''

In [1]:
import math

def isPrime(num):
    if num<=1:
        return False
    for i in range(2,int(math.sqrt(num))+1):
        if num%i==0:
            return False  
    return True

num =int(input('enter a number:'))
print(isPrime(num)) 

enter a number: 2


True


# 3.

In [ ]:
'''write a function is_palindrome(string) that takes a string as input and returns
true if the string reads the same backward as forward (eg.."racecar" is a palindrome)'''

In [2]:
str=input('enter a string:')
def is_palindrome(string):
    rev=string[::-1]
    if rev==string:
        return True
    else:
        return False

is_palindrome(str)
    

enter a string: MADAM


True

# 4.

In [ ]:
'''write a function reverse_list(data) that takes a list as input and
returns a new list with elements in reverse order(eg..reverse_list
([1,2,3]) returns [3,2,1])'''

In [6]:
def reverse_list(data):
    return data[::-1]
    
print(reverse_list([1, 2, 3])) 
print(reverse_list(['a', 'b', 'c'])) 

[3, 2, 1]
['c', 'b', 'a']


# 5.

In [ ]:
'''write a function write_file (filename,content) that takes a filename
and content as input and writes the content to specified file'''

In [5]:
content=input('enter your content:')
def write_file(filename, content):
    with open(filename, 'w') as f:
        f.write(content) 
        print('content has been written!!')
write_file('example.txt',content)

enter your content: Hello!!


content has been written!!


# 6.

In [ ]:
'''  Write a function copy_file(source_filename, destination_filename) that
 takes the source and destination filenames as input and copies the content of the source
 file to the destination file. Handle cases where the source file doesn't exist.'''

In [6]:
def copy_file(source_filename,destination_filename):
    with open('source.txt','r') as s,open('destiantion.txt','w') as d:
        for line in s:
            d.write(line)

In [7]:
copy_file('source.txt','destination.txt')

# 7.

In [ ]:
'''Implement a function to calculate the dot product of two NumPy arrays.'''

In [8]:
import numpy as np
def calculate_dot_product(arr1, arr2):
    return (arr1*arr2)
arr1=np.array([[1,4,6],[5,1,78],[23,56,90]])
arr2=np.array([[23,34,45],[45,56,67],[2,9,4]])
result = calculate_dot_product(arr1, arr2)
print(result) 

[[  23  136  270]
 [ 225   56 5226]
 [  46  504  360]]


# 8.

In [ ]:
'''  Implement a GUI with a radio button selection for choosing a favorite color (e.g., red,
 green, blue). Change the background color of the window based on the selected radio button''' 

In [13]:
import tkinter as tk
from tkinter import ttk


def change_color():
    selected_color = color_var.get()
    top.configure(bg=selected_color)

top=tk.Tk()
top.title('background color')
top.geometry('550x400') 

color_var=tk.StringVar()

colors=['red','green','blue','lavender','skyblue','pink','black']
for color in colors:
    radio_button=ttk.Radiobutton(top,text=color,value=color,variable=color_var
                                ,command=change_color)
    radio_button.pack(anchor=tk.W)


top.mainloop()


# 9.

In [ ]:
'''  Design a currency converter GUI. Allow users to enter an amount and select the
 currencies they want to convert between (e.g., USD, EUR). Display the converted amount in the selected currency'''

In [17]:
import tkinter as tk
from tkinter import ttk, messagebox
import requests

class CurrencyConverter(tk.Tk):
    def __init__(self):
        super().__init__()

        self.title("Currency Converter")
        self.geometry("400x200")

        self.amount_label = tk.Label(self, text="Amount:")
        self.amount_label.grid(row=0, column=0, padx=10, pady=10)
        
        self.amount_entry = tk.Entry(self)
        self.amount_entry.grid(row=0, column=1, padx=10, pady=10)

        self.from_currency_label = tk.Label(self, text="From:")
        self.from_currency_label.grid(row=1, column=0, padx=10, pady=10)
        
        self.from_currency_combobox = ttk.Combobox(self, values=self.get_currency_list())
        self.from_currency_combobox.grid(row=1, column=1, padx=10, pady=10)

        self.to_currency_label = tk.Label(self, text="To:")
        self.to_currency_label.grid(row=2, column=0, padx=10, pady=10)
        
        self.to_currency_combobox = ttk.Combobox(self, values=self.get_currency_list())
        self.to_currency_combobox.grid(row=2, column=1, padx=10, pady=10)

        self.convert_button = tk.Button(self, text="Convert", command=self.convert_currency)
        self.convert_button.grid(row=3, column=1, padx=10, pady=10)

        self.result_label = tk.Label(self, text="Converted Amount:")
        self.result_label.grid(row=4, column=0, padx=10, pady=10)
        
        self.result_value = tk.Label(self, text="")
        self.result_value.grid(row=4, column=1, padx=10, pady=10)

    def get_currency_list(self):
        response = requests.get('https://api.exchangerate-api.com/v4/latest/USD')
        if response.status_code == 200:
            data = response.json()
            return list(data['rates'].keys())
        else:
            messagebox.showerror("Error", "Failed to fetch currency list")
            return []

    def convert_currency(self):
        try:
            amount = float(self.amount_entry.get())
            from_currency = self.from_currency_combobox.get()
            to_currency = self.to_currency_combobox.get()

            response = requests.get(f'https://api.exchangerate-api.com/v4/latest/{from_currency}')
            if response.status_code == 200:
                data = response.json()
                rate = data['rates'][to_currency]
                converted_amount = amount * rate
                self.result_value.config(text=f"{converted_amount:.2f}")
            else:
                messagebox.showerror("Error", "Failed to fetch conversion rate")
        except ValueError:
            messagebox.showerror("Error", "Invalid amount entered")
        except Exception as e:
            messagebox.showerror("Error", str(e))

if __name__ == "__main__":
    app = CurrencyConverter()
    app.mainloop()


In [ ]:
# THANK YOU!!!