In [4]:
import numpy as np

In [5]:
arr=np.array([12,23,45,56,32])

In [6]:
arr

array([12, 23, 45, 56, 32])

In [7]:
print(arr)

[12 23 45 56 32]


In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.dtype

dtype('int32')

In [10]:
arr=np.array([12,23,45,56,32,66.22])

In [11]:
arr.dtype

dtype('float64')

In [12]:
arr

array([12.  , 23.  , 45.  , 56.  , 32.  , 66.22])

In [13]:
print(arr)

[12.   23.   45.   56.   32.   66.22]


In [14]:
arr=np.array([12,23,45,56,32,66.11,'pune'])

In [15]:
arr.dtype

dtype('<U32')

In [16]:
arr

array(['12', '23', '45', '56', '32', '66.11', 'pune'], dtype='<U32')

In [17]:
%%timeit
arr=np.array([12,23,45,56,32])

2 µs ± 99.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [18]:
arr[3]

'56'

In [19]:
arr.shape

(7,)

In [20]:
arr=np.array([12,23,45,56,32])

In [21]:
arr*2

array([ 24,  46,  90, 112,  64])

In [22]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
np.arange(2,10,2.5)

array([2. , 4.5, 7. , 9.5])

In [24]:
np.arange(-5,5,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
#2d

In [28]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr1.ndim

2

In [31]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr1.shape

(3, 3)

In [33]:
arr1.size

9

In [34]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [35]:
arr2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
arr2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [37]:
arr2.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [38]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
arr2[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [40]:
arr

array([12, 23, 45, 56, 32])

In [41]:
arr.mean()

33.6

In [42]:
arr.min()

12

In [43]:
arr.max()

56

In [44]:
arr=np.array([2,1,3,5,6,3,3,1,7])

In [45]:
np.unique(arr)

array([1, 2, 3, 5, 6, 7])

In [46]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [47]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.linalg.det(arr1)

6.66133814775094e-16

In [49]:
np.linalg.inv(arr1)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [50]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr3

array([[ 1,  4,  6],
       [ 5,  1, 78],
       [23, 56, 90]])

In [55]:
arr3=np.array([[1,4,6],[5,1,78],[23,56,90]])

In [57]:
arr1*arr3

array([[  1,   8,  18],
       [ 20,   5, 468],
       [161, 448, 810]])

In [54]:
arr1 @ arr3

array([[  80,  174,  432],
       [ 167,  357,  954],
       [ 254,  540, 1476]])